export const PRODUCT_LIST_REQUEST_PENDING = "PRODUCT_LIST_REQUEST_PENDING";
export const PRODUCT_LIST_REQUEST_SUCCESS = "PRODUCT_LIST_REQUEST_SUCCESS";
export const PRODUCT_LIST_REQUEST_FAILED = "PRODUCT_LIST_REQUEST_FAILED";

export const PRODUCT_DETAILS_REQUEST_PENDING =
  "PRODUCT_DETAILS_REQUEST_PENDING";
export const PRODUCT_DETAILS_REQUEST_SUCCESS =
  "PRODUCT_DETAILS_REQUEST_SUCCESS";
export const PRODUCT_DETAILS_REQUEST_FAILED = "PRODUCT_DETAILS_REQUEST_FAILED";
